//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenHillsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantas
    {
        public int ID { get; set; }
        public string NomeComum { get; set; }
        public string NomeCientifico { get; set; }
        public Nullable<double> TempRecomendada { get; set; }
        public Nullable<double> UmidRecomendada { get; set; }
        public Nullable<double> LumiRecomendada { get; set; }
    }
}
